---
- name: enable apache2 mod rewrite
  apache2_module: name=rewrite state=present
- name: enable apache2 mod alias
  apache2_module: name=alias state=present
- name: enable apache2 mod ssl
  apache2_module: name=ssl state=present
- name: Add apache vhosts configuration.
  template: >
    src=vhosts.conf.j2
    dest={{ apache_conf_path }}/vhost_{{ vhost_name }}.conf
    owner=root group=root mode=644
  notify: restart apache
